=== VeronikaLapenok/java_web_development/task2/resources/data/postcard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="resourses/data"
        xmlns:tns="resourses/data"
        elementFormDefault="qualified">

  <element name="postcards">
    <complexType>
      <sequence>
        <element ref="tns:postcard" minOccurs="16" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
  
  <complexType name="Postcard">
    <sequence>
      <element name="paper" type="tns:Paper"/>
      <element name="country" type="string"/>
      <element name="year" type="date"/>
      <element name="author" type="string"/>
    </sequence>
    
    <attribute name="id" type="tns:Id" use="required"/>
    <attribute name="name" type="string" use="optional" default="no name"/>
  </complexType>

  <simpleType name="Id">
    <restriction base="ID">
      <pattern value="card[0-9]+"/>
    </restriction>
  </simpleType>
  
  <complexType name="common">
    <complexContent>
      <extension base="tns:Postcard">
        <sequence>
          <element name="thema">
            <simpleType>
              <restriction base="string">
                <enumeration value="animals"/>
                <enumeration value="nature"/>
                <enumeration value="art"/>
                <enumeration value="movies"/>
                <enumeration value="famous people"/>
                <enumeration value="architecture"/>
                <enumeration value="maxicards"/>
                <enumeration value="other"/>
              </restriction>
            </simpleType>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="advertising">
    <complexContent>
      <extension base="tns:Postcard">
        <sequence>
          <element name="company" type="string"/>
          <element name="web_site" type="string"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="congratulatory">
    <complexContent>
      <extension base="tns:Postcard">
        <sequence>
          <element name="holiday">
            <simpleType>
              <restriction base="string">
                <enumeration value="Birthday"/>
                <enumeration value="Christmas"/>
                <enumeration value="New Year"/>
                <enumeration value="Victory Day"/>
                <enumeration value="Valentine's Day"/>
                <enumeration value="other"/>
              </restriction>
            </simpleType>
          </element>
          <element name="message" type="string"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Paper">
    <sequence>
      <element name="density" type="positiveInteger"/>
      <element name="is_gloss" type="boolean"/>
      <element name="size" type="tns:Size"/>
    </sequence>
  </complexType>
  
  <complexType name="Size">
    <sequence>
      <element name="length" type="positiveInteger"/>
      <element name="width" type="positiveInteger"/>
    </sequence>
  </complexType>
  
  <element name="postcard" type="tns:Postcard" abstract="true"/>
  <element name="common_postcard" type="tns:common" substitutionGroup="tns:postcard"/>
  <element name="advertising_postcard" type="tns:advertising" substitutionGroup="tns:postcard"/>
  <element name="congratulatory_postcard" type="tns:congratulatory" substitutionGroup="tns:postcard"/>

</schema>

=== VeronikaLapenok/java_web_development/task2/resources/data/postcard.xml
<?xml version="1.0" encoding="UTF-8"?>
<postcards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="resourses/data"
           xsi:schemaLocation="resourses/data postcard.xsd">

  <common_postcard id="card01" name="Squirrel">
    <paper>
      <density>300</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Great Britain</country>
    <year>2019-09-13</year>
    <author>Richard Hood</author>
    <thema>animals</thema>
  </common_postcard>
  
  <common_postcard id="card02" name="Vilnius">
    <paper>
      <density>325</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Lithuania</country>
    <year>2013-10-09</year>
    <author>L. Jankauskas</author>
    <thema>architecture</thema>
  </common_postcard>
  
  <common_postcard id="card03" name="Harry Potter">
    <paper>
      <density>325</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Russia</country>
    <year>2018-07-24</year>
    <author>Grape_Art_Com</author>
    <thema>movies</thema>
  </common_postcard>
  
  <common_postcard id="card04" name="Lynx and lynx kitten">
    <paper>
      <density>325</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Belarus</country>
    <year>2020-12-15</year>
    <author>-</author>
    <thema>maxicards</thema>
  </common_postcard>
  
  <advertising_postcard id="card05" name="Stroke">
    <paper>
      <density>300</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>16</length>
        <width>11</width>
      </size>
    </paper>
    <country>Great Britain</country>
    <year>2009-03-13</year>
    <author>-</author>
    <company>Stroke</company>
    <web_site>stroke.org.uk</web_site>
  </advertising_postcard>
  
  <common_postcard id="card06" name="Schwedt">
    <paper>
      <density>300</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Germany</country>
    <year>1989-05-28</year>
    <author>Zoepffel</author>
    <thema>architecture</thema>
  </common_postcard>
  
  <congratulatory_postcard id="card07" name="Happy birthday">
    <paper>
      <density>325</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Russia</country>
    <year>1991-01-29</year>
    <author>I. Dergileva</author>
    <holiday>Birthday</holiday>
    <message>Happy Birthday!!!</message>
  </congratulatory_postcard>
  
  <common_postcard id="card08" name="Blue cats">
    <paper>
      <density>350</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Belarus</country>
    <year>2017-11-04</year>
    <author>I. Zenyuk</author>
    <thema>art</thema>
  </common_postcard>
  
  <congratulatory_postcard id="card09" name="Marry Christmas">
    <paper>
      <density>325</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Germany</country>
    <year>2001-06-22</year>
    <author>Corazza</author>
    <holiday>Christmas</holiday>
    <message>Marry Christmas!!!</message>
  </congratulatory_postcard>
  
  <common_postcard id="card10" name="Scenery">
    <paper>
      <density>325</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Russia</country>
    <year>1986-03-17</year>
    <author>V. Mitin</author>
    <thema>nature</thema>
  </common_postcard>
  
  <common_postcard id="card11" name="Hotel 'Paris'">
    <paper>
      <density>300</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Belarus</country>
    <year>2016-10-16</year>
    <author>T. Kuznetsova</author>
    <thema>architecture</thema>
  </common_postcard>
  
  <common_postcard id="card12" name="Old Minsk">
    <paper>
      <density>300</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Belarus</country>
    <year>2016-07-25</year>
    <author>T. Kuznetsova</author>
    <thema>architecture</thema>
  </common_postcard>
  
  <advertising_postcard id="card13" name="Animia">
    <paper>
      <density>325</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Belarus</country>
    <year>2018-11-17</year>
    <author>Wikipet</author>
    <company>Wikipet</company>
    <web_site>wikipet.by</web_site>
  </advertising_postcard>
  
  <common_postcard id="card14" name="Greta Garbo">
    <paper>
      <density>325</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Russia</country>
    <year>2014-04-29</year>
    <author>I. Paltser</author>
    <thema>famous people</thema>
  </common_postcard>
  
  <common_postcard id="card15" name="Reiterbildnis">
    <paper>
      <density>325</density>
      <is_gloss>true</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Germany</country>
    <year>2020-08-10</year>
    <author>Jurgen Fuhrmann</author>
    <thema>art</thema>
  </common_postcard>
  
  <advertising_postcard id="card16" name="Gerber">
    <paper>
      <density>325</density>
      <is_gloss>false</is_gloss>
      <size>
        <length>15</length>
        <width>10</width>
      </size>
    </paper>
    <country>Lithuania</country>
    <year>2010-04-13</year>
    <author>Baddog</author>
    <company>Gerber</company>
    <web_site>www.baddog.lt</web_site>
  </advertising_postcard>
  
</postcards>
